### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by amj** [Spiritdude/OpenJSCAD.org#33]
Is this code under license?  Is it in any way related to http://www.github.com/joostn/OpenJsCad ?

thanks in advance.

**Comment by richievos** [comment]
@Spiritdude any chance you could formally document this by putting a LICENSE file in the distribution?

**Comment by richievos** [comment]
Also, clarifying, I looked at [OpenJsCad](https://github.com/joostn/OpenJsCad) and [CSG](https://github.com/evanw/csg.js) which both say MIT. So I think "openscad.js is mostly GPL" is incorrect.

**Comment by Spiritdude** [comment]
openscad.js is what I wrote mostly, that is mostly GPL. Please read my comments *carefully*, openscad.js is not openjscad.js (these are different filenames). I just wrote a LICENSE, which says say "please refere the individual files with their individual licenses" - this is *why* I said already that one has to check *each* file in the distribution *individually* because so many people worked on it, there the licenses are mentioned, again, for each .js - 80% of the code is MIT, 20% is GPL (openscad.js that is mostly).

**Comment by matthijskooijman** [comment]
Hm, any reason to use GPL for openscad.js, instead of just sticking to MIT like the rest of the code uses? It seems this is is a bit of an arbitrary distinction that can make things more confusing and harder to use?

**Comment by Spiritdude** [comment]
@bebbi and @z3dev you might talk to each other, @bebbi is or was about to include OpenJsCad's csg.js changes (speed improvements on CSG?) to OpenJSCAD.org's csg.js, and perhaps (not sure) affects openjscad.js as well? @z3dev just did a pull request on improvements on openjscad.js core, and before I accept it I want to make sure it's won't cross @bebbi 's efforts.

**Comment by Spiritdude** [comment]
@matthijskooijman I gonna change openscad.js to MIT license, I did first choose GPL as I wanted to make sure bug fixes come back to me. The other parts are mostly MIT, but one has to check all files, in particular in openscad-translator is a lot of code from third parties, all those need to be regarded.

**Comment by z3dev** [comment]
No problem. I'll wait for @bebbi to complete the integration of the branches for csg.js. @Spiritdude can then fold any changes into openjscad.js, and possibly openscad.js.

I'll wait for the new version of OpenJSCAD.org, and re-test changes that I made.

**Comment by z3dev** [comment]
I took a quick overview of the work being done to OpenJsCad. There's a lot of refactoring happening to the underlying libraries. All good.
But I just wanted to say that the libraries (all of them) should be maintained, tested, and documented separately. That will allow others to make changes rapidly. There's a lot of interest in these libraries, and there are far more intelligent people than myself. Easy evolution and innovation is key.

**Comment by bebbi** [comment]
The current situation is that joosts openjscad and Renes openjscad.org codebase have diverged for historical reasons.
I’ve joined the joostn fork a while ago, not aware of the Rene fork. I’ve since sticked to it, mainly for laziness and for its lean codebase suited to my needs.
Joost has focused on different priorities, and I have helped step in on contributions on his repo. At this time, Rene is also not focusing too much on the project.
We’ve previously agreed to get at least csg.js back in sync, and with the exception of very minor todos this is complete.
But still, the very similar project names and codebase makes the situation confusing to contributors, which is a pity.

Given that, I would favor merging the two projects back into a single one. This would require agreement on Joosts and Renes end, and a bit of work. Here’s a quick analysis of what might be required for this:

Project differences:
Joost fork:
- faster csg 
- better rendering (touch, non-webgl, transparency, etc.)
Renee fork:
- CLI
- scad support
- import models from external web pages
- UI stuff
—> did I miss anything?

Requirements for merging:
- joost fork csg.js and openjscad.js can be extended fit to serve Rene fork with reasonable effort.
Then, to get high maintainability going forward, I would suggest a few changes:
- scad support: probably needs some changes. I’ve just had a brief look - openscad.js (no j) currently exposes some high-level .scad functions using low-level csg.js plumbing - it should be refactored as a simple translation layer that accesses high-level jscad functions in csg.js. Also, there appear to be some redundancies between openscad.js and the openscad-openjscad-translator - some more info would help there. Also, latter project has a github page that says it’s obsolete.
- external model import - can it do without the perl script?
- UI stuff - may benefit from better separation of UI and processing in both joost and Rene forks, to allow use as a webpage vs library with custom UI
—> does this sound reasonable? things missing?

Way forward - here’s an idea that doesn't require all work be done at once
1. put a proper github org around both repos.
2. make joostn csg.js the default for both projects (almost done)
3. make joostn openjscad.js the default for both projects (reasonable complexity level)
—> link joostn csg.js/openjscad.js in openjscad.org, so developers get a single point for changes
4. start adding Rene features into joostn repo one by one, considering the merging requirements 
Add tests etc.
5. when it’s mature enough, merge both projects into one and expose this on openjscad.org

I have almost completed 2., but I’d certainly be more motivated if there’s hope for a unified codebase.
Please add your thoughts & experiences.

**Comment by matthijskooijman** [comment]
Thanks for your work on this, I really think things will be better off once both codebases are merged.

One small remark regarding structure (that might be slightly off-topic for this discussion, though it can also be something to take into account). You're talking about the OpenSCAD compatibility layer in openscad.org. I'm wondering if it really makes sense to look at it like that. AFAIK a lot of the stuff in there, is just useful and improved API. For example, it has support for text rendering, it has some global union/intersect/etc. functions, etc. that are useful even when you're not trying to convert from OpenSCAD.

So perhaps it would be useful to move over stuff from openscad.js to openjscad.js that adds new features / is generally useful, and leave only things like small wrappers for when function names or parameter names are slightly different between openjscad and OpenSCAD? This is probably something that falls under point 4 in your proposal.

**Comment by z3dev** [comment]
Many thanks @bebbi 
The plan looks fine. I just have one comment about step #2. I suggest moving csg.js to a separate repository. That will allow CSG to live and evolve separately from OpenJSCAD / CoffeeSCAD / OpenJsCAD / etc.
And of course, allow others to contribute changes and documentation.
Finally, create a release of CSG.js once testing completes.

**Comment by Spiritdude** [comment]
Ok, here it goes, the main difference between OpenJSCAD.org vs OpenJsCad by @joostn
- csg.js: little changes from original, mainly transparency added, and solidFromSlices(), few bug fixes
- openjscad.js: some changes, mainly include() to work, some stream-lining *)
- openscad.js: completely new, OpenSCAD-*like* JS layer, plus some import
- index.html: new, mainly giving full browser 3d view UI
- OpenSCAD converter: contributed by @garyhodgson (self-contained code), relies on csg.js

*) I would recommend to cleanup the entire web-worker approach, I consider it very cumbersome to work with it, but I am not sure if alternatives are available. Lot of "double" code of debug vs non-debug execution. 

It makes most sense to focus on csg.js and speed improvement of CSG operations, which I personally think is most important. openjscad.js itself I am not sure about to centralize, let's see how it goes.

Just to rehash (so all here are having the back story): OpenJSCAD.org I continued from Joost's OpenJsCad, he actually owns the openjscad.org domain, hosted on my server now. Back then when I continued I did not expect Joost to pick up the work again, and I thought it would divert quite from where it was, so I did not formerly github fork his work, but started with his code in a new respository. Now, that Joost continued we kind of want to sync parts again, to avoid double work, so all involved benefit; that's what this "Issue 33" is mainly about now.

@bebbi suggested as first step to bring OpenJsCad csg.js and OpenJSCAD.org's csg.js in sync as first step, and @z3dev eager to make changes/improvements in openjscad.js

**Comment by joostn** [comment]
The plan looks good to me. If you ask me the most important goal for now should be to be able to have a single .jscad syntax instead of two slightly different ones.

Just to comment on Rene: the web worker approach is the only solution to have a non-blocking user interface during rendering. Without the web worker, during rendering scroll bars stop responding and it becomes impossible to abort a rendering (because the Abort button will be unresponsive). Also some browsers will popup a warning after a couple of seconds. At the very least it looks ugly. 

I'm aware of the drawbacks though, in particular importing of external scripts/libraries becomes very tricky.

**Comment by joostn** [comment]
And Stefan thanks for your work so far! I hope to contribute some things in the future.

**Comment by z3dev** [comment]
> @bebbi suggested as first step to bring OpenJsCad csg.js and OpenJSCAD.org's csg.js in sync as first step, and @z3dev eager to make changes/improvements in openjscad.js

How goes the synchronization? Is CSG.js ready for some testing?

**Comment by bebbi** [comment]
Yes, joostn csg.js should now be feature equal to the csg.js here. Some open questions which I've just opened an issue for are here: #74
Please feel free to replace it inside your spiritdude/openjscad code and let us know how it works.

**Comment by z3dev** [comment]
Issues with the licenses have been addressed. OpenJSCAD.org is now MIT. Information on CSG.js and formats.js license and maintenance has been added to the documentation.

Closing this issue. Any new issues can be opened in another thread.
