### ISSUE TITLE
TypeError: this.color.join is not a function

### ISSUE THREAD

**Issue by quillford** [Spiritdude/OpenJSCAD.org#95]
Getting the following error on [this](https://raw.githubusercontent.com/quillford/printrcore/printrbot-simple/sources/openjscad/smartcore-v1.2.jscad) file which worked previously.
```
TypeError: this.color.join is not a function
Stack trace:
TypeError: this.color.join is not a function
    at Object.CSG.Polygon.Shared.getHash (http://openjscad.org/csg.js:2944:31)
    at Object.CSG.fuzzyCSGFactory.getPolygonShared (http://openjscad.org/csg.js:4614:37)
    at http://openjscad.org/csg.js:694:47
    at Array.map (native)
    at Object.CSG.reTesselated (http://openjscad.org/csg.js:687:30)
    at Object.CSG.union (http://openjscad.org/csg.js:240:32)
    at union (http://openjscad.org/openscad.js:329:13)
    at motorXY (blob:http%3A//openjscad.org/df4f014f-28ce-4f4e-b2ea-b4df6453ae1d:503:46)
    at main (blob:http%3A//openjscad.org/df4f014f-28ce-4f4e-b2ea-b4df6453ae1d:1287:13)
    at Function.OpenJsCad.runMainInWorker (http://openjscad.org/openjscad.js:580:18)
```

**Comment by z3dev** [comment]
Just to be sure... Browsers cache Javascript files. Please clear your browser cache and try again. This will make sure that all libraries are the most recent.

Thanks.

**Comment by lmw94002** [comment]
I have the exact same issue.  Cleared my cache.  Was there a resolution?

**Comment by thehans** [comment]
I did a little debugging for this.  The code is expecting color.join to be a function, which means it expects color to be an Array, but apparently in this case it is not.  So I set a conditional breakpoint in http://openjscad.org/csg.js:2944 , with the condition: (this.color.constructor !== Array) 

Now it breaks and I can look at the value of color to find that it is set to "grey", a string instead of an Array.  This value is set by line 492 of the example code provided by quilford.  

    cube({size:[9,_nemaXYZ,20]}).setColor("grey"),

So the quick fix is to modify your line of code here to have actual numeric values as all your other setColor calls do.  

However this value shouldn't be allowed to be set in the first place.

Looking into csg.js:setColor function, it calls out to CSG.Polygon.Shared.fromColor, which also only expects array type as input(when a single argument is passed), but the only check it does on single argument input is that the input has a length of 3 (r,g,b) or 4 (r,g,b,a).  Since the string "grey" happens to be 4 characters long, it assumes its a proper array and sets the value.  This function should have an additional type check for arrays and throw an exception at the time of setting if the input is not an array.

**Comment by z3dev** [comment]
That's correct. setColor() expects an array of RGB values.

Solids can be given a color using the setColor() function. setColor() expects an array with 3 or 4
elements [r, g, b, [alpha]]. Beware: this returns a new solid,
the original solid is not modified! Faces of the solid will keep their original color when doing
CSG operations (union() etc). Color values range between 0.0 and 1.0 (not 255). 

There's another function (OpenSCAD-like) called color() which takes a string, i.e. color name.

**Comment by Spiritdude** [comment]
FYI @zdev I just updated csg.js with the latest version from OpenJsCad https://github.com/joostn/OpenJsCad/commit/183ec6684f5b7e7a25773af0130adec58bf6e112

**Comment by Spiritdude** [comment]
Closing this issue?

**Comment by lmw94002** [comment]
Thanks for the help.
